# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a6bf63d1ea6b03a21f1231e60466d30c"
name = "chat-boat"
handle = "chat-boat-1"
application_url = "https://suffer-pts-traveling-willing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "chat-bot-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_product_listings,read_products,write_inventory,write_orders,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://suffer-pts-traveling-willing.trycloudflare.com/auth/callback",
  "https://suffer-pts-traveling-willing.trycloudflare.com/auth/shopify/callback",
  "https://suffer-pts-traveling-willing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
