# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aecc1e39f3be0c08f212c689187ed9c1"
name = "chatui"
handle = "chatui"
application_url = "https://west-wars-leather-windsor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "chat-bot-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://west-wars-leather-windsor.trycloudflare.com/auth/callback",
  "https://west-wars-leather-windsor.trycloudflare.com/auth/shopify/callback",
  "https://west-wars-leather-windsor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
